### ISSUE TITLE
Change Instance(s) to cursor(s)

### ISSUE THREAD

**Issue by mpawliszyn** [cashapp/backfila#50]
I'm finding several people are getting confused on what an instance is. It is a term that is already pretty well overloaded.

I think a better name might be cursor.

**Comment by myronmarston** [comment]
I don't really understand in what way instance is a cursor.  (but I also didn't really understand what an instance was).  Can you explain what role an instance serves?

**Comment by shellderp** [comment]
Instance was a slightly abstracted way to support sharded data sets, which require different cursors to work correctly. Each one has a separate lease and pool of threads so you can think of them as being almost separate backfills aka instances. But really the only difference is having cursors for each one, so cursors is a clearer name

**Comment by myronmarston** [comment]
Are there use cases for them beyond sharded data sets?  Once I dug into the backfila code and realized that the non-sharded cases return one `Instance` while the sharded ones return one `Instance` per shard, I understood their use case, and I thought of an `Instance` as a `BackfillShardSpecification` (or `BackfillShardSpec`).

I get what you're saying about the cursors, but the `Instance`s themselves are not cursors, at least not in any sense I've ever heard the term. I think of a cursor as providing a bookmark within a stream. It specifies a particular point in the stream where consumption was paused and we can pickup again.  That's not really what the `Instance` is, even though the data within it gets used to create a cursor.

Maybe `CursorExtent` or `CursorRange` or something like that?  It seems like it provides a keyspace range that a cursor will later iterate over.

**Comment by mpawliszyn** [comment]
So I really don't like using the word shard. `while the sharded ones return one Instance per shard` isn't quite true, SingleCursor being the exception so far. 

What about fragment? Like its a fragment of a backfill that the cursor iterates over?

**Comment by mpawliszyn** [comment]
Or even better `Partition`

**Comment by myronmarston** [comment]
I like fragment and partition quite a bit.  Although to me "partition" and "shard" are synonyms...

**Comment by shellderp** [comment]
The point was not to tie this to shards, but to have a generic way to have multiple parallel cursors/ranges for the backfill. Shards are just one case where this is needed. I would probably go with "cursor"  as the longer ones aren't any clearer imo

**Comment by myronmarston** [comment]
@shellderp I think "cursor" is confusing as the name because, unless I'm missing something, the `Instance`s are definitely not cursors. They don't point to a particular point in the middle of an iteration like how "cursor" is usually understood to work.  The `Instance`s provide enough data for a cursor to be created to iterate over the entire extent of the `Instance` but the `Instance` itself is not a cursor.

So I think `Cursor` can be in the name, but it needs some suffix, e.g. `CursorRange`, `CursorExtent` or something.

**Comment by mpawliszyn** [comment]
The reason I like partition because it is not shard but it refers to how the backfill is divided up or partitioned. It is a bit synonymous with shard but since we don't use that name elsewhere here I think it is fine. In fact we are trying to do what shard does to database to the backfill so that the words mean similar things should be expected. Maybe in the readme we should just add some of these terms when doing this PR.

Cursor really refers to a bookmark of where it is in processing that chunk of the backfill which is why having a different name than that is useful.

**Comment by shellderp** [comment]
partition, part, chunk, all could work 
https://www.thesaurus.com/browse/part?s=t

**Comment by myronmarston** [comment]
I'm happy with `Partition`, FWIW.

**Comment by mpawliszyn** [comment]
I'm finally getting around to this. Any objections to Partition?
